export const LOGIN = {
    LOGGEDIN_CHECK_STATE: "LOGGEDIN_CHECK_STATE",
    LOGIN_ADMIN: "LOGIN_ADMIN",
    LOGIN: "LOGIN",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    TOKEN_CHECK_TIMEOUT: "TOKEN_CHECK_TIMEOUT",
    LOGOUT: "LOGOUT",
    SET_LOGIN_REDIRECT_PATH: "SET_LOGIN_REDIRECT_PATH",
}